### PR TITLE
Asif ikbal 02 08 2021

### PR DESCRIPTION
**Pull request by aikbal**
Please review week 1 and 2 works. I will create another request tonight after I finish week 3 tasks.

### CODE REVIEW

**Comment by aikbal** [comment]
@rajivsam , Please review.

**Comment by rajivsam** [comment]
@aikbal Create a heat map for each quarter and then use a categorical heat map, not a continuous version.

**Review by rajivsam — COMMENTED** [review]
@aikbal very nice. I like the heat map

**Comment by aikbal** [comment]
@rajivsam , I have appended task-3 for this week in the same notebook week_3_tasks.ipynb . Please review.

**Review by rajivsam — COMMENTED** [review]
Good. Those observations about missing data are correct.

**Comment by aikbal** [comment]
@rajivsam , I have discussed with SK about the week convention and agreed to start the week from Sunday. 

We found that some weeks like week 13, 26, 39 belong to two quarters. If we consider week 13,  from Sunday to Thursday belong to Q1 and Friday, Saturday belong to Q2. SK proposed to keep week 13 in Q1 and Q2 starts from week 14. I proposed to keep it as it is. Week 13 will be in both the the quarter, For Q1, Friday, Saturday will be marked with different colour by assigning -1. For Q2, Sunday to Thursday will be marked in the same way. Assigning -1 to mark with different colour. It simply represent that the day do not belong to the quarter. 

We are unable to decide which should we try. Can you please suggest something?

**Comment by rajivsam** [comment]
@aikbal @Sama-Ko , it really does not matter. All that is relevant is that you a time series of counts for each quarter. Just pick one quarter for the boundary weeks and move on.

**Pull request closed without merging**
