### PR TITLE
Updated weekly worklog

### PR DESCRIPTION
**Pull request by Sama-Ko**

### CODE REVIEW

**Comment by rajivsam** [comment]
@Sama-Ko , pull latest from main, resolve conflicts and then submit the PR again. There are conflicts.

**Comment by Sama-Ko** [comment]
> @Sama-Ko , pull latest from main, resolve conflicts and then submit the PR again. There are conflicts.

@rajivsam but sir I pulled latest from main before submitting the PR.

**Comment by rajivsam** [comment]
@Sama-Ko , you need to:

1. Pull from main
2. MERGE CONFLICTING FILES - worklog.txt. Make sure you are not deleting any lines
3. add, commit changes, push to remote
4. Raise a PR

**Comment by rajivsam** [comment]
@Sama-Ko whenver you see a conflict when you open a PR. It means main was updated since you last pulled and there are conflicting changes in some files. To resolve, you need to pull from main again, resolve the conflicts, push the new branch again and then raise a PR. HTH

**Review by rajivsam — APPROVED** [review]

**Pull request merged**
